couchbase:
    node: 
    - http://localhost:8091/pools
    bucket: default
    password: Tesco@2016

swagger:
  resourcePackage: com.tesco.rs.resource

server:
  applicationConnectors:
  - type: http 
    port: 9080
  adminConnectors:
  - type: http
    port: 9081